### PR TITLE
issue #2 Update Lucene/Solr version to 5.0.0

### PR DESCRIPTION
**Pull request by mocobeta**
4.10.0 jars removed, 5.0.0 jars added, Tokenizers / Filters updated.

### CODE REVIEW

**Comment by johtani** [comment]
Thanks, PR!

Could you please change README.txt?

**Comment by mocobeta** [comment]
Thanks for you response!
I've removed those four lines and changed README.
Could you please check it. Thanks.

**Comment by johtani** [comment]
@mocobeta Sorry for late reply. I left one comment.

**Comment by johtani** [comment]
We need to add checking condition, like this.
https://github.com/apache/lucene-solr/blob/branch_5x/lucene/analysis/kuromoji/src/java/org/apache/lucene/analysis/ja/JapanesePartOfSpeechStopFilterFactory.java#L54-54

And we have to delete enablePositionIncrements option from Java Doc and sample snippet.

**Comment by mocobeta** [comment]
Thanks comments,
I've fixed README.txt and example snippets for schema.xml to follow changes in Solr directory structure, and removed obsoleted enablePositionIncrements option.
Lucene version checks were added to FilterFactorys (according to kuromoji.)

**Comment by johtani** [comment]
@mocobeta  Thanks! merged to master.

**Pull request merged**
